---
mysql_debian_pkgs:
  # Note that mysql 5.6 is installed from a non standard PPA in tasks/main.yml
  # It is not listed here because of non-standard steps required to install
  # mysql 5.6 on 12.04
  - python-mysqldb


mysql_databases:
  - db: "{{ ECOMMERCE_DEFAULT_DB_NAME | default(None) }}"
  - db: "{{ INSIGHTS_DATABASE_NAME | default(None) }}"
  - db: "{{ ORA_MYSQL_DB_NAME | default(None) }}"
  - db: "{{ XQUEUE_MYSQL_DB_NAME | default(None) }}"
  - db: "{{ EDXAPP_MYSQL_DB_NAME | default(None) }}"
  - db: "{{ EDX_NOTES_API_MYSQL_DB_NAME | default(None) }}"
  - db: "{{ PROGRAMS_DEFAULT_DB_NAME | default(None) }}"
  - db: "{{ ANALYTICS_API_DEFAULT_DB_NAME | default(None) }}"
  - db: "{{ ANALYTICS_API_REPORTS_DB_NAME | default(None) }}"
#  - db: "{{ HIVE_METASTORE_DATABASE.name | default(None) }}"
#    encoding: "latin1"


mysql_database_users:
  - {
      db: "{{ ECOMMERCE_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ ECOMMERCE_DATABASES.default.USER | default(None) }}",
      pass: "{{ ECOMMERCE_DATABASES.default.PASSWORD | default(None) }}"
      priv: "{{ ECOMMERCE_DEFAULT_DB_NAME | default(None) }}.*:ALL"
    }
  - {
      db: "{{ INSIGHTS_DATABASE_NAME | default(None) }}",
      user: "{{ INSIGHTS_DATABASES.default.USER | default(None) }}",
      pass: "{{ INSIGHTS_DATABASES.default.PASSWORD | default(None) }}"
      priv: "{{ INSIGHTS_DATABASE_NAME | default(None) }}.*:ALL"
    }
  - {
      db: "{{ XQUEUE_MYSQL_DB_NAME | default(None) }}",
      user: "{{ XQUEUE_MYSQL_USER | default(None) }}",
      pass: "{{ XQUEUE_MYSQL_PASSWORD | default(None) }}"
      priv: "{{ XQUEUE_MYSQL_DB_NAME | default(None) }}.*:ALL"
    }
  - {
      db: "{{ EDXAPP_MYSQL_DB_NAME | default(None) }}",
      user: "{{ EDXAPP_MYSQL_USER | default(None) }}",
      pass: "{{ EDXAPP_MYSQL_PASSWORD | default(None) }}"
      priv: "{{ EDXAPP_MYSQL_DB_NAME | default(None) }}.*:ALL"
    }
  - {
      db: "{{ PROGRAMS_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ PROGRAMS_DATABASES.default.USER | default(None) }}",
      pass: "{{ PROGRAMS_DATABASES.default.PASSWORD | default(None) }}"
      priv: "{{ PROGRAMS_DEFAULT_DB_NAME | default(None) }}.*:ALL"
    }
  - {
      db: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE_NAME | default(None) }}",
      user: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE.username }}",
      pass: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE.password }}"
      priv: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE_NAME | default(None) }}.*:ALL"
    }
  - {
      db: "{{ HIVE_METASTORE_DATABASE_NAME | default(None) }}",
      user: "{{ HIVE_METASTORE_DATABASE.user | default(None) }}",
      pass: "{{ HIVE_METASTORE_DATABASE.password | default(None) }}"
      priv: "{{ HIVE_METASTORE_DATABASE_NAME | default(None) }}.*:ALL"
    }
  - {
      db: "{{ ANALYTICS_API_DEFAULT_DB_NAME | deafult(None) }}"
      user: "api001"
      pass: "{{ ANALYTICS_API_DATABASES.default.PASSWORD }}"
      priv: "{{ ANALYTICS_API_DATABASES.default.NAME }}.*:ALL/reports.*:SELECT"
    }
  - {
      db: "{{ ANALYTICS_API_REPORTS_DB_NAME | deafult(None) }}"
      user: "api001"
      pass: "{{ ANALYTICS_API_DATABASES.reports.PASSWORD }}"
      priv: "{{ ANALYTICS_API_DATABASES.reports.NAME }}.*:SELECT"
    }
