# Installs packages to run edx locally on a single instance
#
---

- name: create a database for the hive metastore
  mysql_db: >
    db={{ HIVE_METASTORE_DATABASE.name }}
    state=present
    encoding=latin1
  when: HIVE_METASTORE_DATABASE is defined

- name: setup the edx-notes-api db user
  mysql_user: >
    name={{ EDX_NOTES_API_MYSQL_DB_USER }}
    password={{ EDX_NOTES_API_MYSQL_DB_PASS }}
    priv='{{ EDX_NOTES_API_MYSQL_DB_NAME }}.*:SELECT,INSERT,UPDATE,DELETE'
  when: EDX_NOTES_API_MYSQL_DB_USER is defined


- name: setup the read-only db user
  mysql_user: >
    name={{ COMMON_MYSQL_READ_ONLY_USER }}
    password={{ COMMON_MYSQL_READ_ONLY_PASS }}
    priv='*.*:ALL'

- name: setup the admin db user
  mysql_user: >
    name={{ COMMON_MYSQL_ADMIN_USER }}
    password={{ COMMON_MYSQL_ADMIN_PASS }}
    priv='*.*:CREATE USER'


- name: install memcached
  apt: pkg=memcached state=present
